// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Actor struct {
	ID           string             `json:"id"`
	NamespaceID  string             `json:"namespace_id"`
	ActorKey     string             `json:"actor_key"`
	Revision     int32              `json:"revision"`
	Kind         string             `json:"kind"`
	Protocol     string             `json:"protocol"`
	EndpointRef  pgtype.Text        `json:"endpoint_ref"`
	Capabilities []byte             `json:"capabilities"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Artifact struct {
	ID             string             `json:"id"`
	NamespaceID    string             `json:"namespace_id"`
	RunID          pgtype.Text        `json:"run_id"`
	AttemptID      pgtype.Text        `json:"attempt_id"`
	Uri            string             `json:"uri"`
	MediaType      pgtype.Text        `json:"media_type"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	Digest         pgtype.Text        `json:"digest"`
	StorageBackend string             `json:"storage_backend"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Attempt struct {
	ID            string             `json:"id"`
	NamespaceID   string             `json:"namespace_id"`
	NodeRunID     string             `json:"node_run_id"`
	AttemptNumber int32              `json:"attempt_number"`
	ActorID       pgtype.Text        `json:"actor_id"`
	Status        string             `json:"status"`
	FencingToken  pgtype.Int8        `json:"fencing_token"`
	Result        []byte             `json:"result"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type Event struct {
	ID            string             `json:"id"`
	NamespaceID   string             `json:"namespace_id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	Sequence      int64              `json:"sequence"`
	EventType     string             `json:"event_type"`
	Source        string             `json:"source"`
	Data          []byte             `json:"data"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type HumanTask struct {
	ID              string             `json:"id"`
	NamespaceID     string             `json:"namespace_id"`
	RunID           string             `json:"run_id"`
	NodeRunID       pgtype.Text        `json:"node_run_id"`
	Kind            string             `json:"kind"`
	AssignedOwnerID pgtype.Text        `json:"assigned_owner_id"`
	Status          string             `json:"status"`
	Request         []byte             `json:"request"`
	Response        []byte             `json:"response"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
}

type IdempotencyKey struct {
	ID             string             `json:"id"`
	NamespaceID    string             `json:"namespace_id"`
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestDigest  pgtype.Text        `json:"request_digest"`
	Response       []byte             `json:"response"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type LedgerProjectionVersion struct {
	ID             string             `json:"id"`
	NamespaceID    string             `json:"namespace_id"`
	RunID          string             `json:"run_id"`
	ProjectionKind string             `json:"projection_kind"`
	LedgerVersion  int64              `json:"ledger_version"`
	Digest         string             `json:"digest"`
	Data           []byte             `json:"data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type LedgerRecord struct {
	ID             string             `json:"id"`
	NamespaceID    string             `json:"namespace_id"`
	SchemaVersion  string             `json:"schema_version"`
	RecordType     string             `json:"record_type"`
	RunID          pgtype.Text        `json:"run_id"`
	NodeRunID      pgtype.Text        `json:"node_run_id"`
	AttemptID      pgtype.Text        `json:"attempt_id"`
	OriginKind     string             `json:"origin_kind"`
	OriginActorID  pgtype.Text        `json:"origin_actor_id"`
	Authority      string             `json:"authority"`
	SubjectRef     pgtype.Text        `json:"subject_ref"`
	Data           []byte             `json:"data"`
	ProvenanceRefs []byte             `json:"provenance_refs"`
	Supersedes     pgtype.Text        `json:"supersedes"`
	ContentDigest  string             `json:"content_digest"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type LedgerReview struct {
	ID                    string             `json:"id"`
	NamespaceID           string             `json:"namespace_id"`
	RunID                 string             `json:"run_id"`
	ReviewerActorID       pgtype.Text        `json:"reviewer_actor_id"`
	ReviewedLedgerVersion int64              `json:"reviewed_ledger_version"`
	FrameChecksum         string             `json:"frame_checksum"`
	Decision              string             `json:"decision"`
	RecordIds             []byte             `json:"record_ids"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type Namespace struct {
	ID          string             `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type NodeRun struct {
	ID          string             `json:"id"`
	NamespaceID string             `json:"namespace_id"`
	RunID       string             `json:"run_id"`
	TokenID     pgtype.Text        `json:"token_id"`
	NodeKey     string             `json:"node_key"`
	Status      string             `json:"status"`
	Outcome     pgtype.Text        `json:"outcome"`
	VisitCount  int32              `json:"visit_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Outbox struct {
	ID          string             `json:"id"`
	NamespaceID string             `json:"namespace_id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Attempts    int32              `json:"attempts"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Owner struct {
	ID          string             `json:"id"`
	NamespaceID string             `json:"namespace_id"`
	Kind        string             `json:"kind"`
	ExternalRef pgtype.Text        `json:"external_ref"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID                string             `json:"id"`
	NamespaceID       string             `json:"namespace_id"`
	WorkflowVersionID string             `json:"workflow_version_id"`
	Status            string             `json:"status"`
	Input             []byte             `json:"input"`
	StartedByActorID  pgtype.Text        `json:"started_by_actor_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type RunnerOperation struct {
	ID            string             `json:"id"`
	NamespaceID   string             `json:"namespace_id"`
	AttemptID     pgtype.Text        `json:"attempt_id"`
	OperationKind string             `json:"operation_kind"`
	PolicyDigest  string             `json:"policy_digest"`
	Request       []byte             `json:"request"`
	Result        []byte             `json:"result"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type Timer struct {
	ID          string             `json:"id"`
	NamespaceID string             `json:"namespace_id"`
	RunID       pgtype.Text        `json:"run_id"`
	NodeRunID   pgtype.Text        `json:"node_run_id"`
	TimerKind   string             `json:"timer_kind"`
	FireAt      pgtype.Timestamptz `json:"fire_at"`
	Status      string             `json:"status"`
	ClaimedBy   pgtype.Text        `json:"claimed_by"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Token struct {
	ID            string             `json:"id"`
	NamespaceID   string             `json:"namespace_id"`
	RunID         string             `json:"run_id"`
	NodeKey       string             `json:"node_key"`
	State         string             `json:"state"`
	ParentTokenID pgtype.Text        `json:"parent_token_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
}

type WorkItem struct {
	ID             string             `json:"id"`
	NamespaceID    string             `json:"namespace_id"`
	NodeRunID      string             `json:"node_run_id"`
	State          string             `json:"state"`
	StateVersion   int64              `json:"state_version"`
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	FencingToken   int64              `json:"fencing_token"`
	Attempt        int32              `json:"attempt"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowDraft struct {
	ID           string             `json:"id"`
	NamespaceID  string             `json:"namespace_id"`
	WorkflowKey  string             `json:"workflow_key"`
	OwnerID      pgtype.Text        `json:"owner_id"`
	SourceFormat string             `json:"source_format"`
	Source       string             `json:"source"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowVersion struct {
	ID                 string             `json:"id"`
	NamespaceID        string             `json:"namespace_id"`
	WorkflowKey        string             `json:"workflow_key"`
	Version            int32              `json:"version"`
	DraftID            pgtype.Text        `json:"draft_id"`
	OwnerID            pgtype.Text        `json:"owner_id"`
	SourceFormat       string             `json:"source_format"`
	Source             string             `json:"source"`
	NormalizedIr       []byte             `json:"normalized_ir"`
	ContentDigest      string             `json:"content_digest"`
	PublishedByActorID pgtype.Text        `json:"published_by_actor_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
