// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (id, slug, display_name)
VALUES ($1, $2, $3)
RETURNING id, slug, display_name, created_at
`

type CreateNamespaceParams struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, createNamespace, arg.ID, arg.Slug, arg.DisplayName)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowVersion = `-- name: CreateWorkflowVersion :one
INSERT INTO workflow_versions (
    id, namespace_id, workflow_key, version, draft_id, owner_id,
    source_format, source, normalized_ir, content_digest, published_by_actor_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, namespace_id, workflow_key, version, draft_id, owner_id,
    source_format, source, normalized_ir, content_digest, published_by_actor_id, created_at
`

type CreateWorkflowVersionParams struct {
	ID                 string      `json:"id"`
	NamespaceID        string      `json:"namespace_id"`
	WorkflowKey        string      `json:"workflow_key"`
	Version            int32       `json:"version"`
	DraftID            pgtype.Text `json:"draft_id"`
	OwnerID            pgtype.Text `json:"owner_id"`
	SourceFormat       string      `json:"source_format"`
	Source             string      `json:"source"`
	NormalizedIr       []byte      `json:"normalized_ir"`
	ContentDigest      string      `json:"content_digest"`
	PublishedByActorID pgtype.Text `json:"published_by_actor_id"`
}

func (q *Queries) CreateWorkflowVersion(ctx context.Context, arg CreateWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersion,
		arg.ID,
		arg.NamespaceID,
		arg.WorkflowKey,
		arg.Version,
		arg.DraftID,
		arg.OwnerID,
		arg.SourceFormat,
		arg.Source,
		arg.NormalizedIr,
		arg.ContentDigest,
		arg.PublishedByActorID,
	)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.WorkflowKey,
		&i.Version,
		&i.DraftID,
		&i.OwnerID,
		&i.SourceFormat,
		&i.Source,
		&i.NormalizedIr,
		&i.ContentDigest,
		&i.PublishedByActorID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowVersion = `-- name: GetWorkflowVersion :one
SELECT id, namespace_id, workflow_key, version, draft_id, owner_id,
    source_format, source, normalized_ir, content_digest, published_by_actor_id, created_at
FROM workflow_versions
WHERE id = $1
`

func (q *Queries) GetWorkflowVersion(ctx context.Context, id string) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersion, id)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.WorkflowKey,
		&i.Version,
		&i.DraftID,
		&i.OwnerID,
		&i.SourceFormat,
		&i.Source,
		&i.NormalizedIr,
		&i.ContentDigest,
		&i.PublishedByActorID,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    id, namespace_id, aggregate_type, aggregate_id, sequence, event_type, source, data, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, namespace_id, aggregate_type, aggregate_id, sequence, event_type, source, data, occurred_at
`

type InsertEventParams struct {
	ID            string             `json:"id"`
	NamespaceID   string             `json:"namespace_id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	Sequence      int64              `json:"sequence"`
	EventType     string             `json:"event_type"`
	Source        string             `json:"source"`
	Data          []byte             `json:"data"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.NamespaceID,
		arg.AggregateType,
		arg.AggregateID,
		arg.Sequence,
		arg.EventType,
		arg.Source,
		arg.Data,
		arg.OccurredAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Sequence,
		&i.EventType,
		&i.Source,
		&i.Data,
		&i.OccurredAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (
    id, namespace_id, topic, payload, status, available_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, namespace_id, topic, payload, status, available_at, published_at, attempts, created_at
`

type InsertOutboxParams struct {
	ID          string             `json:"id"`
	NamespaceID string             `json:"namespace_id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutbox,
		arg.ID,
		arg.NamespaceID,
		arg.Topic,
		arg.Payload,
		arg.Status,
		arg.AvailableAt,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Topic,
		&i.Payload,
		&i.Status,
		&i.AvailableAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const nextEventSequence = `-- name: NextEventSequence :one
SELECT (COALESCE(MAX(sequence), 0) + 1)::bigint AS next_sequence
FROM events
WHERE aggregate_id = $1
`

func (q *Queries) NextEventSequence(ctx context.Context, aggregateID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextEventSequence, aggregateID)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}
