// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateNamespace(ctx context.Context, arg CreateNamespaceParams) (Namespace, error)
	CreateWorkflowVersion(ctx context.Context, arg CreateWorkflowVersionParams) (WorkflowVersion, error)
	GetWorkflowVersion(ctx context.Context, id string) (WorkflowVersion, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) (Outbox, error)
	NextEventSequence(ctx context.Context, aggregateID string) (int64, error)
}

var _ Querier = (*Queries)(nil)
