import { describe, expect, it } from "vitest";
import type { MeshPayload } from "../api/client";
import type { NodeRunListItem, Run, WorkflowVersion } from "../api/types";
import { assembleMeshGraph, meshEventAction } from "./mesh";
const mesh: MeshPayload = { version: "v1", workers: [{ worker_id: "w1", hostname: "thor", revision: "a", actor_keys: ["company/dev"], last_seen: "now" }, { worker_id: "w2", hostname: "orin", revision: "b", actor_keys: ["company/review", "human/ori"], last_seen: "now" }], machines: { thor: { actors: ["company/dev"] }, orin: { actors: ["company/review"] } }, actors: [{ actor_key: "company/dev", machine: "thor", bridge: { observed_at: "now", error: "probe timed out" } }, { actor_key: "company/review", machine: "orin", bridge: { observed_at: "now", deployment: {} } }, { actor_key: "human/ori", machine: null, bridge: { observed_at: "now", deployment: {} } }] };
const workflow = (digest: string, version: number): WorkflowVersion => ({ id: `wv${version}`, workflow_key: "ship", version, digest, source: "", source_format: "yaml", created_at: "now", normalized_ir: { spec: { entry: "work", nodes: { work: { kind: "agent", uses: "actor://company/dev@sha256:old" }, approve: { kind: "approval", approverRef: "actor://human/ori" } }, edges: [] } } });
const run: Run = { id: "r1", workflow_digest: "d3", state: "running", created_at: "now", updated_at: "now" };
const nr: NodeRunListItem = { id: "nr1", run_id: "r1", node_id: "work", actor_id: "company/dev", state: "running", created_at: "now", updated_at: "now", usage: { input_tokens: 0, output_tokens: 0, cached_input_tokens: 0, reasoning_tokens: 0, attempts_reported: 0, attempts_not_reported: 0 } };
describe("assembleMeshGraph", () => {
  it("builds typed nodes, groups versions, and emits only recorded relations", () => { const graph = assembleMeshGraph(mesh, [run], [nr], [workflow("d1", 1), workflow("d2", 2), workflow("d3", 3)]); expect(graph.nodes.map((n) => n.kind)).toEqual(expect.arrayContaining(["machine", "control-plane", "bridge", "human", "workflow", "run"])); expect(graph.nodes.find((n) => n.kind === "workflow")?.versionCount).toBe(3); expect(graph.edges.map((e) => e.relation).sort()).toEqual(["actor-machine", "actor-machine", "actor-workflow", "run-actor", "run-workflow"].sort()); });
  it("keeps failed probes unknown and machine-null actors unattributed", () => { const graph = assembleMeshGraph(mesh, [], [], []); expect(graph.nodes.find((n) => n.actorKey === "company/dev")).toMatchObject({ status: "unknown", error: "probe timed out" }); expect(graph.nodes.find((n) => n.actorKey === "human/ori")?.sub).toBe("unattributed"); expect(graph).toMatchObject({ machineCount: 2, probeFailures: 1, unattributedActors: 1 }); expect(graph.nodes.find((n) => n.label === "thor")?.sub).not.toBe(graph.nodes.find((n) => n.label === "orin")?.sub); });
});
it("maps one committed event to one relevant run pulse", () => { expect(meshEventAction({ id: "e", source: "x", specversion: "1", type: "dev.culture.nodes.ledger.record-appended", subject: "r1", time: "now", datacontenttype: "application/json", data: { run_id: "r1" } })).toEqual({ kind: "pulse", runId: "r1", direction: "inbound" }); });
