#!/usr/bin/env bash
# Regenerate the measured trigger-condition-action migration inventory.
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"
python3 - "$@" <<'PY'
import argparse
import json
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser(description="Regenerate the TCA migration inventory")
parser.add_argument("--output", type=Path, default=Path("docs/migration/tca-inventory.md"))
args = parser.parse_args()

tracked = sorted(filter(None, subprocess.check_output(["git", "ls-files", "-z"]).decode().split("\0")))


def workflow_file(path):
    name = Path(path).name
    if path.startswith("schemas/workflow/"):
        return path.endswith(".json")
    if path.startswith("schemas/examples/"):
        return "workflow" in name and path.endswith(".json")
    if "/__golden__/" in path and path.startswith("web/"):
        return True
    return (path.startswith("examples/") or "/testdata/" in path) and "workflow" in name and Path(path).suffix in (".yaml", ".yml", ".json")


# The BEFORE state is measured at the spec commit, not the working tree, so
# it stays true while the build adds the very things it says are absent
# (honesty condition h44). The per-file table below stays live: it is where
# migration progress is tracked.
BEFORE = "51dd46a13aa9a955e83a3ef9418b6b3c588e36e1"


def before_tracked():
    return sorted(filter(None, subprocess.check_output(["git", "ls-tree", "-r", "-z", "--name-only", BEFORE]).decode().split("\0")))


def before_text(path):
    return subprocess.check_output(["git", "show", f"{BEFORE}:{path}"]).decode(errors="replace")


files = [path for path in tracked if workflow_file(path)]
before_files = before_tracked()
definitions = [path for path in before_files if workflow_file(path) and Path(path).suffix in (".yaml", ".yml", ".json") and not path.startswith("schemas/workflow/")]
schema = json.loads(before_text("schemas/workflow/workflow.schema.json"))
kinds = schema["$defs"]["node"]["properties"]["kind"]["enum"]

# Read runtime sources, not the design docs where future names already appear.
event_sources = [path for path in before_files if path.startswith(("internal/", "examples/", "adapters/")) and Path(path).suffix in (".go", ".py", ".yaml", ".json")]
approved = any("github.pr.approved" in before_text(path) for path in event_sources)
github_actor = any(path.startswith("adapters/github/") for path in before_files)

print(f"workflow files: {len(definitions)}")
print(f"node kinds: {len(kinds)} ({', '.join(kinds)})")
print(f"github.pr.approved trigger: {'present' if approved else 'absent'}")
print(f"GitHub messaging actor: {'present' if github_actor else 'absent'}")

lines = [
    "# Trigger-condition-action migration inventory",
    "",
    "Generated by `scripts/tca-inventory.sh` from tracked files (`git ls-files`). Run the script again after adding or removing a workflow fixture. Parity status describes declaration-era behavior; `pending` means it has not been demonstrated yet.",
    "",
    f"## Measured before state (spec commit `{BEFORE[:7]}`)",
    "",
    f"- Workflow definition and fixture files: **{len(definitions)}**. The table also includes schema files and golden diff fixtures.",
    f"- Node kinds in `schemas/workflow/workflow.schema.json`: **{len(kinds)}** ({', '.join('`' + kind + '`' for kind in kinds)}).",
    f"- `github.pr.approved` runtime trigger: **{'present' if approved else 'absent'}**.",
    f"- GitHub messaging actor (`adapters/github/`): **{'present' if github_actor else 'absent'}**.",
    "",
    "The graph engine pins a workflow digest per run. The declaration engine will pin trigger, condition and action version digests per firing. Existing runs keep their graph read paths during the drain.",
    "",
    "## Workflow files and fixtures",
    "",
    "| Tracked file | Target declaration form | Parity status |",
    "|---|---|---|",
]

for path in files:
    if path.startswith("schemas/workflow/"):
        form = "Declaration schema or handoff contract; replace graph shape checks"
    elif path.startswith("schemas/examples/"):
        form = "Equivalent example of named trigger, condition, action and nodes"
    elif "/__golden__/" in path:
        form = "Declaration editor round trip or graph-view golden"
    elif path.startswith("internal/compiler/testdata/"):
        form = "Declaration validation fixture with equivalent accept/reject result"
    elif path.startswith("internal/worker/testdata/"):
        form = "Action dispatch and node lifecycle fixture with equivalent outcome"
    elif path.startswith("internal/engine/testdata/"):
        form = "Trigger, lineage and node lifecycle fixture with equivalent outcome"
    elif "/testdata/" in path:
        form = "Declaration fixture with equivalent behavior or validation result"
    else:
        form = "Split workflow trigger, CEL guards and actions into linked declarations"
    lines.append(f"| `{path}` | {form} | pending |")

lines += [
    "",
    "## Configuration and source generation (c61 and c62)",
    "",
    "| Current item | Target declaration form | Parity status |",
    "|---|---|---|",
    "| schedules (`internal/scheduler/schedules.go`) | `timer` trigger to the scheduled action | pending |",
    "| notifier posts (`internal/notifier/`) | lifecycle event trigger to `discord.post` action | pending |",
    "| repair routing (`internal/repair/`) | failure trigger, bounded condition and repair action | pending |",
    "| hand-turns (`schemas/ledger/hand_turn_definition.schema.json`) | `human.ask` action and `human.decision` reaction | pending |",
    "| affinity (`internal/compiler/affinity.go`) | Actor selection on the declaration action | pending |",
    "| workflow generation (`internal/api/workflow_generations.go`) | Generate proposed declaration source and diagnostics | pending |",
    "| devague plan import (`cmd/nodes/planimport.go`, `/v1alpha1/plan-imports`) | Import plan as proposed declarations and links | pending |",
    "",
    "## Run-surface consumers",
    "",
    "The current read path remains available until each consumer has a declaration-era read path. `run` maps to lineage, `node run` to firing, `attempt` to action attempt, and token movement to lineage; an open declaration node is the waiting state.",
    "",
    "| Consumer / current read path | Target declaration form | Parity status |",
    "|---|---|---|",
]

for endpoint, target in (
    ("runs", "List lineages and their firings; keep graph-run reads during drain"),
    ("node-runs", "List firings and action attempts across lineages"),
    ("human-tasks", "List open `human.ask` nodes and decisions"),
    ("pending-decisions", "List outstanding human decision nodes"),
    ("tickets", "Resolve ticket context through verified lineage"),
):
    lines.append(f"| web UI `/v1alpha1/{endpoint}` (`web/src/api/client.ts`) | {target} | pending; graph read path retained |")

for event in ("created", "completed", "failed", "cancelled", "bounded"):
    lines.append(f"| nodes-notifier `dev.culture.nodes.run.{event}` (`internal/notifier/lifecycle.go`) | Lineage or firing lifecycle event to `discord.post`; keep graph event delivery | pending; graph read path retained |")

lines += [
    "| `scripts/collect-handover.py` run/node-run/attempt detail | Resolve lineage, firing and action attempt for handover; keep graph detail reads | pending; graph read path retained |",
    "| nodes-operator (`.claude/skills/nodes-operator/scripts/nodes-op.sh`) run/node-run/attempt detail | Resolve lineage, firing and action attempt for operator commands; keep graph detail reads | pending; graph read path retained |",
    "",
]

args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text("\n".join(lines))
PY
