#!/usr/bin/env python3
"""Render the open-issue triage table and reject missing dispositions."""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
import time
from pathlib import Path

# GitHub answers 503 often enough to matter: this check ran six times in one
# cycle and failed twice on a transient API error, once turning a PR red for a
# reason unrelated to its change. A retry is what actually stops that.
GH_ATTEMPTS = 4
GH_BACKOFF_SECONDS = 3


class GitHubUnreachable(RuntimeError):
    """The open-issue set could not be READ. Distinct from a stale table.

    Folding the two together is the same defect scripts/lint-all.sh was just
    corrected for: "could not check" must not render as "checked and it is
    wrong". This one exits 2 -- the code merge-gate.py uses for
    measurement_incomplete and _errors.py reserves for an environment error.
    """

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TABLE = ROOT / "docs" / "triage" / "dispositions.csv"
DEFAULT_OUTPUT = ROOT / "docs" / "triage" / "open-issues.md"
BUCKETS = {
    "verify-then-close",
    "operator-lane enablers",
    "bug tail",
    "finish work",
    "owner decisions",
    "large bets",
}


def open_issue_numbers(repo: str, issues_json: Path | None) -> list[int]:
    if issues_json:
        raw = issues_json.read_text(encoding="utf-8")
    else:
        command = [
            "gh", "issue", "list", "--repo", repo, "--state", "open",
            "--limit", "1000", "--json", "number",
        ]
        last = ""
        for attempt in range(1, GH_ATTEMPTS + 1):
            proc = subprocess.run(command, check=False, text=True, capture_output=True)
            if proc.returncode == 0:
                raw = proc.stdout
                break
            last = (proc.stderr or proc.stdout).strip().splitlines()[-1:] or [""]
            last = last[0]
            if attempt < GH_ATTEMPTS:
                print(
                    f"triage-report: gh failed ({last}); retry {attempt}/{GH_ATTEMPTS - 1}",
                    file=sys.stderr,
                )
                time.sleep(GH_BACKOFF_SECONDS * attempt)
        else:
            raise GitHubUnreachable(
                f"could not read the open-issue set after {GH_ATTEMPTS} attempts: {last}"
            )
    data = json.loads(raw)
    return sorted({int(item["number"]) for item in data})


def dispositions(path: Path) -> dict[int, dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    required = {"issue", "bucket", "disposition", "evidence_pointer"}
    if not rows or set(rows[0]) != required:
        raise ValueError(f"{path}: expected columns {sorted(required)}")
    result: dict[int, dict[str, str]] = {}
    for line, row in enumerate(rows, 2):
        issue = int(row["issue"])
        if issue in result:
            raise ValueError(f"{path}:{line}: duplicate issue #{issue}")
        if row["bucket"] not in BUCKETS:
            raise ValueError(f"{path}:{line}: unknown bucket {row['bucket']!r}")
        if not row["disposition"].strip() or not row["evidence_pointer"].strip():
            raise ValueError(f"{path}:{line}: disposition and evidence pointer are required")
        result[issue] = row
    return result


def render(numbers: list[int], rows: dict[int, dict[str, str]]) -> str:
    lines = [
        "# Open-issue triage",
        "",
        "Generated by `python3 scripts/triage-report.py`. Do not edit this file by hand.",
        "",
        "| Issue | Bucket | Disposition | Evidence pointer |",
        "|---:|---|---|---|",
    ]
    for number in numbers:
        row = rows[number]
        values = [row[key].replace("|", "\\|") for key in ("bucket", "disposition", "evidence_pointer")]
        lines.append(f"| #{number} | {values[0]} | {values[1]} | {values[2]} |")
    lines.extend(["", f"Open issues with dispositions: {len(numbers)}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default="agentculture/culture-nodes")
    parser.add_argument("--table", type=Path, default=DEFAULT_TABLE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--issues-json", type=Path, help="offline fixture in gh JSON shape")
    parser.add_argument("--check", action="store_true", help="require output to be up to date")
    args = parser.parse_args()

    try:
        numbers = open_issue_numbers(args.repo, args.issues_json)
        rows = dispositions(args.table)
    except (
        GitHubUnreachable,
        KeyError,
        OSError,
        TypeError,
        ValueError,
        json.JSONDecodeError,
        subprocess.CalledProcessError,
    ) as exc:
        print(f"triage-report: {exc}", file=sys.stderr)
        # 2 == could not measure. A stale table or a missing disposition is a
        # finding and returns 1 further down; this is the absence of a reading.
        return 2

    missing = sorted(set(numbers) - set(rows))
    if missing:
        print("triage-report: open issues have no disposition: " + ", ".join(f"#{n}" for n in missing), file=sys.stderr)
        return 1

    content = render(numbers, rows)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != content:
            print(f"triage-report: {args.output} is stale; regenerate it", file=sys.stderr)
            return 1
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content, encoding="utf-8")
    print(f"triage-report: {len(numbers)} open issues, all dispositioned; output {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
